export const HOME = 'HOME';
export const SPLASH_SCREEN = 'SPLASH_SCREEN';

export const SIGNIN_SCREEN = 'SIGNIN_SCREEN';
export const SIGNUP_SCREEN = 'SIGNUP_SCREEN';

export const NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN';
export const YOUR_ACCOUNT_SCREEN = 'YOUR_ACCOUNT_SCREEN';
export const DELETE_ACCOUNT_SCREEN = 'DELETE_ACCOUNT_SCREEN';
